// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "KinectInterp.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* KinectInterpProto_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  KinectInterpProto_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_KinectInterp_2eproto() {
  protobuf_AddDesc_KinectInterp_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "KinectInterp.proto");
  GOOGLE_CHECK(file != NULL);
  KinectInterpProto_descriptor_ = file->message_type(0);
  static const int KinectInterpProto_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KinectInterpProto, active_skeletons_),
  };
  KinectInterpProto_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      KinectInterpProto_descriptor_,
      KinectInterpProto::default_instance_,
      KinectInterpProto_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KinectInterpProto, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(KinectInterpProto, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(KinectInterpProto));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_KinectInterp_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    KinectInterpProto_descriptor_, &KinectInterpProto::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_KinectInterp_2eproto() {
  delete KinectInterpProto::default_instance_;
  delete KinectInterpProto_reflection_;
}

void protobuf_AddDesc_KinectInterp_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022KinectInterp.proto\"-\n\021KinectInterpProt"
    "o\022\030\n\020active_skeletons\030\001 \003(\010", 67);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "KinectInterp.proto", &protobuf_RegisterTypes);
  KinectInterpProto::default_instance_ = new KinectInterpProto();
  KinectInterpProto::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_KinectInterp_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_KinectInterp_2eproto {
  StaticDescriptorInitializer_KinectInterp_2eproto() {
    protobuf_AddDesc_KinectInterp_2eproto();
  }
} static_descriptor_initializer_KinectInterp_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int KinectInterpProto::kActiveSkeletonsFieldNumber;
#endif  // !_MSC_VER

KinectInterpProto::KinectInterpProto()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void KinectInterpProto::InitAsDefaultInstance() {
}

KinectInterpProto::KinectInterpProto(const KinectInterpProto& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void KinectInterpProto::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

KinectInterpProto::~KinectInterpProto() {
  SharedDtor();
}

void KinectInterpProto::SharedDtor() {
  if (this != default_instance_) {
  }
}

void KinectInterpProto::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* KinectInterpProto::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return KinectInterpProto_descriptor_;
}

const KinectInterpProto& KinectInterpProto::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_KinectInterp_2eproto();  return *default_instance_;
}

KinectInterpProto* KinectInterpProto::default_instance_ = NULL;

KinectInterpProto* KinectInterpProto::New() const {
  return new KinectInterpProto;
}

void KinectInterpProto::Clear() {
  active_skeletons_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool KinectInterpProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated bool active_skeletons = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_active_skeletons:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 1, 8, input, this->mutable_active_skeletons())));
        } else if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag)
                   == ::google::protobuf::internal::WireFormatLite::
                      WIRETYPE_LENGTH_DELIMITED) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, this->mutable_active_skeletons())));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(8)) goto parse_active_skeletons;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void KinectInterpProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated bool active_skeletons = 1;
  for (int i = 0; i < this->active_skeletons_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(
      1, this->active_skeletons(i), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* KinectInterpProto::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // repeated bool active_skeletons = 1;
  for (int i = 0; i < this->active_skeletons_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteBoolToArray(1, this->active_skeletons(i), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int KinectInterpProto::ByteSize() const {
  int total_size = 0;
  
  // repeated bool active_skeletons = 1;
  {
    int data_size = 0;
    data_size = 1 * this->active_skeletons_size();
    total_size += 1 * this->active_skeletons_size() + data_size;
  }
  
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void KinectInterpProto::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const KinectInterpProto* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const KinectInterpProto*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void KinectInterpProto::MergeFrom(const KinectInterpProto& from) {
  GOOGLE_CHECK_NE(&from, this);
  active_skeletons_.MergeFrom(from.active_skeletons_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void KinectInterpProto::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void KinectInterpProto::CopyFrom(const KinectInterpProto& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KinectInterpProto::IsInitialized() const {
  
  return true;
}

void KinectInterpProto::Swap(KinectInterpProto* other) {
  if (other != this) {
    active_skeletons_.Swap(&other->active_skeletons_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata KinectInterpProto::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = KinectInterpProto_descriptor_;
  metadata.reflection = KinectInterpProto_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
